version: "2"

services:
  arthur:
    restart: always
    build: 
      context: ./src
      dockerfile: dockerfile
    container_name: resume
    environment:
      - VIRTUAL_HOST=arthur.juchereau.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=arthur.juchereau.com
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
networks:
  default:
    external:
      name: arthur_default
